# -*- coding: utf-8 -*-
"""ASD  .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVo2kCYf_a_8hidXI4lj-FaKPgxKXXHn

#   ASD ( AI Structural Designer ) is an AI-powered system that takes an

---

architectural plan and automatically produces a  BOQ ,reinforcement details , and PDF reports
"""

# !pip install fpdf

# 📦 Full Agentic Virtual Structural Engineer System (Updated for OpenAI SDK >= 1.0.0)

import cv2
import numpy as np
from fpdf import FPDF
from itertools import combinations
from openai import OpenAI
import pandas as pd
import tkinter as tk
from tkinter import filedialog, messagebox
from PIL import Image, ImageTk

# 🔧 GPT API Key Setup (Replace with your own)
client = OpenAI(api_key="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")

# ========== Step 1: Process Architectural Plan ==========
def extract_columns(image_path):
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    _, thresh = cv2.threshold(img, 200, 255, cv2.THRESH_BINARY_INV)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    columns = []
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        if 10 < w < 200 and 10 < h < 200:
            cx, cy = x + w//2, y + h//2
            columns.append((cx, cy))
    print(f"Total detected columns: {len(columns)}")
    return columns

# ========== Step 2: Generate Beams ==========
def generate_beams(columns):
    beams = []
    for (x1, y1), (x2, y2) in combinations(columns, 2):
        if x1 == x2 or y1 == y2:
            dist = np.hypot(x2 - x1, y2 - y1)
            if dist < 500:
                beams.append(((x1, y1), (x2, y2)))
    return beams

# ========== GPT Agents ==========
def ask_gpt(prompt, role="expert"):
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": f"You are a structural {role}."},
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content.strip()

def ask_gpt_slab_type(columns):
    prompt = f"Suggest slab type for layout with columns: {columns}"
    return ask_gpt(prompt, "engineer")

def ask_gpt_boq(columns, beams):
    prompt = f"Estimate BOQ for {len(columns)} columns and {len(beams)} beams. Provide quantities."
    return ask_gpt(prompt, "estimator")

def ask_gpt_rebar(columns, beams):
    prompt = f"Suggest rebar strategy for structure with {len(columns)} columns and {len(beams)} beams."
    return ask_gpt(prompt, "detailing expert")

def ask_gpt_foundation(columns):
    prompt = f"Suggest foundation type for {len(columns)} columns."
    return ask_gpt(prompt, "foundation expert")

# ========== Step 6: Generate PDF Report ==========
class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 12)
        self.cell(0, 10, "Structural Design Report", ln=True, align="C")
    def chapter(self, title, text):
        self.set_font("Arial", "B", 12)
        self.cell(0, 10, title, ln=True)
        self.set_font("Arial", "", 11)
        self.multi_cell(0, 10, text)

def generate_pdf_report(columns, beams, slab_type, boq, rebar, foundation):
    pdf = PDF()
    pdf.add_page()
    pdf.chapter("Number of Columns:", str(len(columns)))
    pdf.chapter("Number of Beams:", str(len(beams)))
    pdf.chapter("Slab Type:", slab_type)
    pdf.chapter("Foundation Type:", foundation)
    pdf.chapter("BOQ Estimate:", boq)
    pdf.chapter("Rebar Strategy:", rebar)
    pdf.output("design_report.pdf")

# ========== Step 7: Export BOQ to Excel ==========
def export_boq_excel(boq_text, filename="boq.xlsx"):
    lines = boq_text.split("\n")
    items = [line.strip().lstrip("-•") for line in lines if line.strip()]
    data = [item.split(":", 1) if ":" in item else [item, ""] for item in items]
    df = pd.DataFrame(data, columns=["Item", "Quantity"])
    df.to_excel(filename, index=False)

# ========== Step 8: Full Pipeline ==========
def full_pipeline(image_path):
    columns = extract_columns(image_path)
    if not columns:
        return "Error: No columns found."
    beams = generate_beams(columns)
    slab_type = ask_gpt_slab_type(columns)
    boq = ask_gpt_boq(columns, beams)
    rebar = ask_gpt_rebar(columns, beams)
    foundation = ask_gpt_foundation(columns)
    export_boq_excel(boq)
    generate_pdf_report(columns, beams, slab_type, boq, rebar, foundation)
    return "Design completed. Files saved."

# ========== Step 9: GUI ==========
def launch_gui():
    def run_analysis():
        file_path = filedialog.askopenfilename()
        if file_path:
            result = full_pipeline(file_path)
            messagebox.showinfo("Done", result)

    root = tk.Tk()
    root.title("Virtual Structural Engineer")
    root.geometry("400x200")

    tk.Label(root, text="Select Architectural Plan", font=("Arial", 12)).pack(pady=10)
    tk.Button(root, text="Choose Image", command=run_analysis).pack(pady=5)
    tk.Label(root, text="Output: PDF, Excel", font=("Arial", 10)).pack(pady=10)

    root.mainloop()

# ✅ Start GUI
# Uncomment below to launch GUI
# launch_gui()

def clean_text(text):
    return text.encode('latin-1', 'replace').decode('latin-1')

# result = full_pipeline("/content/06193578-c50e-420c-9d3b-fc76ef8a5f4b.jpg")
# print(result)
# ========== Streamlit Interface ==========
import streamlit as st
import os

st.set_page_config(page_title="AI Structural Designer", layout="centered")

st.title("🏗️ AI Structural Designer (ASD)")
st.write("Upload an architectural plan image to generate BOQ, reinforcement, and PDF report.")

uploaded_file = st.file_uploader("📤 Upload architectural plan", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    temp_path = "uploaded_image.jpg"
    with open(temp_path, "wb") as f:
        f.write(uploaded_file.read())

    if st.button("🚀 Start Analysis"):
        result = full_pipeline(temp_path)
        st.success(result)

        if os.path.exists("boq.xlsx"):
            with open("boq.xlsx", "rb") as f:
                st.download_button("📥 Download BOQ (Excel)", f, file_name="boq.xlsx")
        if os.path.exists("design_report.pdf"):
            with open("design_report.pdf", "rb") as f:
                st.download_button("📥 Download Report (PDF)", f, file_name="design_report.pdf")
